{
 "title": "Micrometer Application",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "range_options",
    "query": "1ms,1s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "range_uri", "query": "uri" },
   { "name": "multivalue_test", "query": "1,20,myvalue" },
   { "name": "exception_name", "query": "label_values(exception_name)" }
  ]
 },
 "panels": [
  {
   "title": "Throughput of Micrometer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Throughput" }
   ],
   "targets": [
    {
     "expr": "rate(my_requests_seconds_count[$range_options])",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Service Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "µs", "label": "Latency" }
   ],
   "targets": [
    {
     "expr": "rate(my_requests_seconds_sum[$range_options])/rate(my_requests_seconds_count[$range_options])",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Uptime of Micrometer Application",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "UP" }
   ],
   "targets": [
    { "expr": "up{job='micrometer'}", "legendFormat": "{{job}} @ {{instance}} " }
   ]
  },
  {
   "title": "Top 10 API of Application",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "No of Request" }
   ],
   "targets": [
    {
     "expr": "topk(10, my_requests_seconds_count)",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Histogram Quantile 99% (Schedule Job)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(schedule_job1_seconds_bucket[$range_options])) by (le))",
     "legendFormat": "schedule job1"
    }
   ]
  },
  {
   "title": "Rate of Scheduled Job",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(schedule_job2_seconds_sum[$range_options])"
    }
   ]
  }
 ]
}